services:
  service-backup-agent:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: service-backup-agent
    restart: unless-stopped

    env_file:
      - .env

    environment:
      CONFIG_FILE: /config/services.json
      BACKUP_ROOT: /backups
      LOG_ROOT: /logs
      STATE_ROOT: /state
      ENV_FILE: /app-env/.env
      TZ: Asia/Jerusalem
      WEB_PORT: "9100"

    network_mode: host

    volumes:
      - ./config:/config
      - ./.env:/app-env/.env:rw
      - ./backups:/backups
      - ./logs:/logs
      - ./state:/state
